name: flutter_mediator_example
description: Example project for flutter_mediator

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.0

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  # cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_i18n: ^0.34.0
  flutter_mediator:
    path: ../
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/flutter_i18n/
