name: flutter_mediator
description: Flutter mediator is a state management package base on the InheritedModel with automatic aspect management.
version: 2.2.1
homepage: https://github.com/rob333/flutter_mediator

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
