name: flutter_mediator
description: Flutter mediator is a signal state management package base on the InheritedModel with automatic aspect management.
version: 2.2.5
homepage: https://github.com/rob333/flutter_mediator

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
