name: flutter_mediator
description: Flutter mediator is a state management package base on the InheritedModel with automatic aspect management.
version: 2.1.2+2
homepage: https://github.com/rob333/flutter_mediator

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
