name: example_global_mode
description: Demonstration the usage of Global Mode.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_i18n: ^0.31.1
  flutter_mediator:
    path: ../
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/trees.png
    - assets/flutter_i18n/
